services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password_maestra
      MARIADB_DATABASE: CentroAdopcion
      MARIADB_USER: user_perro
      MARIADB_PASSWORD: password123
    ports:
      - "3306:3306"